spring:
  application:
    name: ${project.artifactId}
  profiles:
    active: dev
  #    using optional for now to boot up application developing process, in the end, optional will be removed
  config:
    import: optional:configserver:http://localhost:8090

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
