grpc:
  server:
    port: 5275

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/publisherdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: test

recordsPopulationCount: 3