grpc:
  server:
    port: 5265

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: libraryDB
      username: admin
      password: admin
      authentication-database: admin
      auto-index-creation: true

recordsPopulationCount: 3