spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/bookdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: test
grpc:
  server:
    port: 6285
  client:
    authorService:
      address: 'static://127.0.0.1:5265'
      negotiation-type: plaintext
      enable-keep-alive:
    publisherService:
      address: 'static://127.0.0.1:5275'
      negotiation-type: plaintext